apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-k8s-2
  name: hello-k8s-2
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx
    name: hello-k8s-2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
