apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-k8s
  name: my-k8s
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx
    name: my-k8s
    ports:
    - containerPort: 80
